import { afterEach, describe, expect, it, vi } from "vitest";
import { createBitbucketWorkflowPR, listBitbucketBranches, listBitbucketRepos } from "./bitbucket-api";

afterEach(() => {
  vi.restoreAllMocks();
});

describe("Bitbucket API helpers", () => {
  it("lists repositories from each accessible workspace", async () => {
    vi.spyOn(globalThis, "fetch")
      .mockResolvedValueOnce(
        Response.json({
          values: [{ workspace: { slug: "team" } }],
          next: "https://api.bitbucket.org/2.0/user/workspaces?page=2"
        })
      )
      .mockResolvedValueOnce(Response.json({ values: [{ workspace: { slug: "tools" } }] }))
      .mockResolvedValueOnce(
        Response.json({
          values: [
            {
              uuid: "{repo-1}",
              slug: "app",
              full_name: "team/app",
              workspace: { slug: "team" },
              is_private: true,
              mainbranch: { name: "main" },
              updated_on: "2026-05-01T00:00:00Z",
              links: { html: { href: "https://bitbucket.org/team/app" } }
            }
          ]
        })
      )
      .mockResolvedValueOnce(
        Response.json({
          values: [
            {
              uuid: "{repo-2}",
              slug: "worker",
              full_name: "tools/worker",
              workspace: { slug: "tools" },
              is_private: false,
              updated_on: "2026-05-02T00:00:00Z",
              links: { html: { href: "https://bitbucket.org/tools/worker" } }
            }
          ]
        })
      );

    const repos = await listBitbucketRepos("token");

    expect(repos.map(repo => repo.fullName)).toEqual(["tools/worker", "team/app"]);
    expect(repos[0]).toMatchObject({
      id: "{repo-2}",
      owner: "tools",
      defaultBranch: "main"
    });
  });

  it("normalizes Bitbucket branches", async () => {
    vi.spyOn(globalThis, "fetch").mockResolvedValueOnce(
      Response.json({
        values: [{ name: "main" }, { name: "develop" }]
      })
    );

    await expect(listBitbucketBranches("team", "app", "token")).resolves.toEqual([
      { name: "main", protected: false },
      { name: "develop", protected: false }
    ]);
  });

  it("creates a Bitbucket branch, commits the pipeline file, and opens a pull request", async () => {
    vi.spyOn(Date, "now").mockReturnValue(1770000000000);
    const fetch = vi
      .spyOn(globalThis, "fetch")
      .mockResolvedValueOnce(Response.json({ mainbranch: { name: "main" } }))
      .mockResolvedValueOnce(Response.json({ name: "add-pipery-build-1770000000000" }, { status: 201 }))
      .mockResolvedValueOnce(Response.json({ hash: "abc123" }, { status: 201 }))
      .mockResolvedValueOnce(
        Response.json(
          {
            links: { html: { href: "https://bitbucket.org/team/app/pull-requests/7" } }
          },
          { status: 201 }
        )
      );

    await expect(
      createBitbucketWorkflowPR({
        workspace: "team",
        repo: "app",
        workflowName: "build",
        yamlContent: "pipelines: {}\n",
        token: "token"
      })
    ).resolves.toEqual({
      prUrl: "https://bitbucket.org/team/app/pull-requests/7",
      branch: "add-pipery-build-1770000000000",
      commit: "abc123"
    });

    expect(fetch).toHaveBeenNthCalledWith(
      2,
      "https://api.bitbucket.org/2.0/repositories/team/app/refs/branches",
      expect.objectContaining({
        method: "POST",
        body: JSON.stringify({
          name: "add-pipery-build-1770000000000",
          target: { hash: "main" }
        })
      })
    );

    const srcRequest = fetch.mock.calls[2][1] as RequestInit;
    expect(srcRequest.method).toBe("POST");
    expect(String(srcRequest.body)).toContain("branch=add-pipery-build-1770000000000");
    expect(String(srcRequest.body)).toContain("%2Fbitbucket-pipelines.yml=pipelines%3A+%7B%7D%0A");

    expect(fetch).toHaveBeenNthCalledWith(
      4,
      "https://api.bitbucket.org/2.0/repositories/team/app/pullrequests",
      expect.objectContaining({
        method: "POST",
        body: JSON.stringify({
          title: "Add build Pipery workflow",
          description: "Generated by [Pipery Workflow Generator](https://start.pipery.dev).",
          source: { branch: { name: "add-pipery-build-1770000000000" } },
          destination: { branch: { name: "main" } },
          close_source_branch: true
        })
      })
    );
  });
});
