import { Branch, Repo } from "./github-api";

const BITBUCKET_API_BASE = process.env.BITBUCKET_API_BASE || "https://api.bitbucket.org/2.0";

interface BitbucketWorkspaceAccess {
  slug?: string;
  workspace?: {
    slug?: string;
  };
}

interface BitbucketRepo {
  uuid?: string;
  slug: string;
  full_name: string;
  workspace?: {
    slug?: string;
  };
  is_private: boolean;
  mainbranch?: {
    name?: string;
  };
  updated_on: string;
  links?: {
    html?: {
      href?: string;
    };
  };
}

interface BitbucketBranch {
  name: string;
}

interface BitbucketPullRequest {
  links?: {
    html?: {
      href?: string;
    };
  };
}

interface BitbucketCommit {
  hash?: string;
}

async function bitbucketRequest<T>(path: string, token: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${BITBUCKET_API_BASE}${toBitbucketPath(path)}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/json",
      ...(init.headers || {})
    }
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Bitbucket API ${response.status}: ${text || response.statusText}`);
  }

  return response.json() as Promise<T>;
}

function toBitbucketPath(pathOrUrl: string) {
  if (!pathOrUrl.startsWith("http")) return pathOrUrl;

  const url = new URL(pathOrUrl);
  return `${url.pathname}${url.search}`;
}

async function bitbucketPaged<T>(path: string, token: string): Promise<T[]> {
  const values: T[] = [];
  let nextPath = path;

  while (nextPath) {
    const payload = await bitbucketRequest<{ values?: T[]; next?: string }>(nextPath, token);
    values.push(...(payload.values || []));
    nextPath = payload.next || "";
  }

  return values;
}

function repoPath(workspace: string, repoSlug: string) {
  return `/repositories/${encodeURIComponent(workspace)}/${encodeURIComponent(repoSlug)}`;
}

export async function listBitbucketRepos(token: string): Promise<Repo[]> {
  const workspaces = await bitbucketPaged<BitbucketWorkspaceAccess>("/user/workspaces?pagelen=100", token);
  const reposById = new Map<string, BitbucketRepo>();

  for (const workspace of workspaces) {
    const workspaceSlug = workspace.workspace?.slug || workspace.slug;
    if (!workspaceSlug) continue;

    const repos = await bitbucketPaged<BitbucketRepo>(
      `/repositories/${encodeURIComponent(workspaceSlug)}?role=member&sort=-updated_on&pagelen=100`,
      token
    );

    for (const repo of repos) {
      reposById.set(repo.uuid || repo.full_name, repo);
    }
  }

  return Array.from(reposById.values())
    .map(repo => ({
      id: repo.uuid || repo.full_name,
      name: repo.slug,
      fullName: repo.full_name,
      owner: repo.workspace?.slug || repo.full_name.split("/")[0],
      private: repo.is_private,
      defaultBranch: repo.mainbranch?.name || "main",
      updatedAt: repo.updated_on,
      url: repo.links?.html?.href || `https://bitbucket.org/${repo.full_name}`
    }))
    .sort((left, right) => Date.parse(right.updatedAt || "0") - Date.parse(left.updatedAt || "0"));
}

export async function listBitbucketBranches(workspace: string, repoSlug: string, token: string): Promise<Branch[]> {
  const branches = await bitbucketPaged<BitbucketBranch>(`${repoPath(workspace, repoSlug)}/refs/branches?pagelen=100`, token);

  return branches.map(branch => ({
    name: branch.name,
    protected: false
  }));
}

export async function createBitbucketWorkflowPR({
  workspace,
  repo,
  workflowName,
  yamlContent,
  token
}: {
  workspace: string;
  repo: string;
  workflowName: string;
  yamlContent: string;
  token: string;
}) {
  const repository = await bitbucketRequest<BitbucketRepo>(repoPath(workspace, repo), token);
  const baseBranch = repository.mainbranch?.name || "main";
  const branch = `add-pipery-${workflowName}-${Date.now()}`;
  const filePath = "bitbucket-pipelines.yml";

  await bitbucketRequest(`${repoPath(workspace, repo)}/refs/branches`, token, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      name: branch,
      target: { hash: baseBranch }
    })
  });

  const body = new URLSearchParams({
    branch,
    message: `add ${workflowName} pipery workflow`,
    [`/${filePath}`]: yamlContent
  });

  const commit = await bitbucketRequest<BitbucketCommit>(`${repoPath(workspace, repo)}/src`, token, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body
  });

  const pr = await bitbucketRequest<BitbucketPullRequest>(`${repoPath(workspace, repo)}/pullrequests`, token, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      title: `Add ${workflowName} Pipery workflow`,
      description: "Generated by [Pipery Workflow Generator](https://start.pipery.dev).",
      source: { branch: { name: branch } },
      destination: { branch: { name: baseBranch } },
      close_source_branch: true
    })
  });

  return { prUrl: pr.links?.html?.href, branch, commit: commit.hash };
}
