import { Octokit } from "@octokit/rest";

export interface Repo {
  id: number | string;
  name: string;
  fullName: string;
  owner: string;
  private: boolean;
  defaultBranch: string;
  updatedAt: string;
  url: string;
}

export interface Branch {
  name: string;
  protected: boolean;
}

function getOctokit(token: string) {
  return new Octokit({ auth: token });
}

function formatWorkflowWriteError(error: any, path: string) {
  const scopes = error.response?.headers?.["x-oauth-scopes"];
  const scopeHint = scopes ? ` Current token scopes: ${scopes}.` : "";

  if (error.status === 404 && path.startsWith(".github/workflows/")) {
    return new Error(
      `GitHub rejected writing ${path}. Reconnect GitHub so Pipery receives the workflow OAuth scope, then try creating the PR again.${scopeHint}`
    );
  }

  return error;
}

export async function listRepos(token: string): Promise<Repo[]> {
  const octokit = getOctokit(token);
  const { data: repos } = await octokit.repos.listForAuthenticatedUser({
    sort: "updated",
    per_page: 100,
    affiliation: "owner,collaborator,organization_member"
  });

  return repos.map((repo: any) => ({
    id: repo.id,
    name: repo.name,
    fullName: repo.full_name,
    owner: repo.owner.login,
    private: repo.private,
    defaultBranch: repo.default_branch,
    updatedAt: repo.updated_at,
    url: repo.html_url
  }));
}

export async function listBranches(owner: string, repo: string, token: string): Promise<Branch[]> {
  const octokit = getOctokit(token);
  const { data: branches } = await octokit.repos.listBranches({
    owner,
    repo,
    per_page: 100
  });

  return branches.map((branch: any) => ({
    name: branch.name,
    protected: branch.protected
  }));
}

export async function createWorkflowPR({
  owner,
  repo,
  workflowName,
  yamlContent,
  token
}: {
  owner: string;
  repo: string;
  workflowName: string;
  yamlContent: string;
  token: string;
}) {
  console.log("[GITHUB-API] Starting PR creation:", { owner, repo, workflowName });
  const octokit = getOctokit(token);
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const baseBranch = repoData.default_branch;
  const { data: baseRef } = await octokit.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
  const branch = `add-pipery-${workflowName}-${Date.now()}`;
  const path = `.github/workflows/${workflowName}.yml`;

  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branch}`,
    sha: baseRef.object.sha
  });

  let existingSha: string | undefined;
  try {
    const { data } = await octokit.repos.getContent({ owner, repo, path, ref: branch });
    if (!Array.isArray(data) && data.type === "file") {
      existingSha = data.sha;
    }
  } catch (error: any) {
    if (error.status !== 404) throw error;
  }

  try {
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path,
      branch,
      message: `add ${workflowName} pipery workflow`,
      content: Buffer.from(yamlContent, "utf8").toString("base64"),
      sha: existingSha
    });
  } catch (error: any) {
    throw formatWorkflowWriteError(error, path);
  }

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    title: `Add ${workflowName} Pipery workflow`,
    head: branch,
    base: baseBranch,
    body: `Generated by [Pipery Workflow Generator](https://start.pipery.dev).\n\n## What this adds\n\n- Workflow file: \`${path}\`\n- Powered by Pipery GitHub Actions`
  });

  return { prUrl: pr.html_url, branch };
}
