const API_ROOT = "https://api.github.com";
const DEFAULT_HEADERS = {
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28"
};

export interface Repo {
  id: number;
  name: string;
  fullName: string;
  owner: string;
  private: boolean;
  defaultBranch: string;
  updatedAt: string;
  url: string;
}

export interface Branch {
  name: string;
  protected: boolean;
}

async function requestGitHub(pathname: string, token: string) {
  const response = await fetch(`${API_ROOT}${pathname}`, {
    headers: { ...DEFAULT_HEADERS, Authorization: `Bearer ${token}` }
  });

  const payload = await response.json();
  if (!response.ok) throw new Error(payload.message || `GitHub request failed for ${pathname}`);
  return payload;
}

async function requestGitHubPost(pathname: string, token: string, body: unknown) {
  const response = await fetch(`${API_ROOT}${pathname}`, {
    method: "POST",
    headers: { ...DEFAULT_HEADERS, Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify(body)
  });

  const payload = await response.json();
  if (!response.ok) throw new Error(payload.message || `GitHub request failed for ${pathname}`);
  return payload;
}

export async function listRepos(token: string): Promise<Repo[]> {
  const repos = await requestGitHub(
    "/user/repos?sort=updated&per_page=100&affiliation=owner,collaborator,organization_member",
    token
  );

  return repos.map((repo: any) => ({
    id: repo.id,
    name: repo.name,
    fullName: repo.full_name,
    owner: repo.owner.login,
    private: repo.private,
    defaultBranch: repo.default_branch,
    updatedAt: repo.updated_at,
    url: repo.html_url
  }));
}

export async function listBranches(owner: string, repo: string, token: string): Promise<Branch[]> {
  const branches = await requestGitHub(`/repos/${owner}/${repo}/branches?per_page=100`, token);

  return branches.map((branch: any) => ({
    name: branch.name,
    protected: branch.protected
  }));
}

export async function createWorkflowPR({
  owner,
  repo,
  workflowName,
  yamlContent,
  token
}: {
  owner: string;
  repo: string;
  workflowName: string;
  yamlContent: string;
  token: string;
}) {
  const repoData = await requestGitHub(`/repos/${owner}/${repo}`, token);
  const baseBranch = repoData.default_branch;
  const baseRef = await requestGitHub(`/repos/${owner}/${repo}/git/ref/heads/${baseBranch}`, token);
  const baseSha = baseRef.object.sha;
  const baseCommit = await requestGitHub(`/repos/${owner}/${repo}/git/commits/${baseSha}`, token);

  const blob = await requestGitHubPost(`/repos/${owner}/${repo}/git/blobs`, token, {
    content: Buffer.from(yamlContent).toString("base64"),
    encoding: "base64"
  });

  const tree = await requestGitHubPost(`/repos/${owner}/${repo}/git/trees`, token, {
    base_tree: baseCommit.tree.sha,
    tree: [{ path: `.github/workflows/${workflowName}.yml`, mode: "100644", type: "blob", sha: blob.sha }]
  });

  const commit = await requestGitHubPost(`/repos/${owner}/${repo}/git/commits`, token, {
    message: `add ${workflowName} pipery workflow\n\nGenerated by Pipery Workflow Generator.`,
    tree: tree.sha,
    parents: [baseSha]
  });

  const newBranch = `add-pipery-${workflowName}-${Date.now()}`;
  await requestGitHubPost(`/repos/${owner}/${repo}/git/refs`, token, {
    ref: `refs/heads/${newBranch}`,
    sha: commit.sha
  });

  const pr = await requestGitHubPost(`/repos/${owner}/${repo}/pulls`, token, {
    title: `Add ${workflowName} Pipery workflow`,
    head: newBranch,
    base: baseBranch,
    body: `Generated by [Pipery Workflow Generator](https://create.pipery.dev).\n\n## What this adds\n\n- CI: \`${workflowName}\`\n- Powered by Pipery GitHub Actions`
  });

  return { prUrl: pr.html_url, branch: newBranch };
}
