import { Branch, Repo } from "./github-api";

const GITLAB_API_BASE = process.env.GITLAB_API_BASE || "https://gitlab.com/api/v4";

async function gitlabRequest<T>(path: string, token: string, init: RequestInit = {}): Promise<T> {
  const response = await fetch(`${GITLAB_API_BASE}${path}`, {
    ...init,
    headers: {
      "PRIVATE-TOKEN": token,
      "Content-Type": "application/json",
      ...(init.headers || {})
    }
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`GitLab API ${response.status}: ${text || response.statusText}`);
  }

  return response.json() as Promise<T>;
}

export async function listGitLabProjects(token: string): Promise<Repo[]> {
  const projects = await gitlabRequest<any[]>(
    "/projects?membership=true&simple=true&order_by=last_activity_at&sort=desc&per_page=100",
    token
  );

  return projects.map(project => ({
    id: project.id,
    name: project.name,
    fullName: project.path_with_namespace,
    owner: project.namespace?.full_path || "",
    private: project.visibility !== "public",
    defaultBranch: project.default_branch || "main",
    updatedAt: project.last_activity_at,
    url: project.web_url
  }));
}

export async function listGitLabBranches(projectId: string, token: string): Promise<Branch[]> {
  const branches = await gitlabRequest<any[]>(
    `/projects/${encodeURIComponent(projectId)}/repository/branches?per_page=100`,
    token
  );

  return branches.map(branch => ({
    name: branch.name,
    protected: branch.protected
  }));
}

export async function createWorkflowMR({
  projectId,
  workflowName,
  yamlContent,
  token
}: {
  projectId: string;
  workflowName: string;
  yamlContent: string;
  token: string;
}) {
  const project = await gitlabRequest<any>(`/projects/${encodeURIComponent(projectId)}`, token);
  const baseBranch = project.default_branch || "main";
  const branch = `add-pipery-${workflowName}-${Date.now()}`;
  const filePath = ".gitlab-ci.yml";
  const encodedProjectId = encodeURIComponent(projectId);
  const encodedFilePath = encodeURIComponent(filePath);
  const fileExists = await fetch(
    `${GITLAB_API_BASE}/projects/${encodedProjectId}/repository/files/${encodedFilePath}?ref=${encodeURIComponent(baseBranch)}`,
    { headers: { "PRIVATE-TOKEN": token } }
  ).then(response => response.ok);

  const commit = await gitlabRequest<any>(`/projects/${encodedProjectId}/repository/commits`, token, {
    method: "POST",
    body: JSON.stringify({
      branch,
      start_branch: baseBranch,
      commit_message: `add ${workflowName} pipery workflow`,
      actions: [
        {
          action: fileExists ? "update" : "create",
          file_path: filePath,
          content: yamlContent
        }
      ]
    })
  });

  const mr = await gitlabRequest<any>(`/projects/${encodedProjectId}/merge_requests`, token, {
    method: "POST",
    body: JSON.stringify({
      source_branch: branch,
      target_branch: baseBranch,
      title: `Add ${workflowName} Pipery workflow`,
      description: "Generated by [Pipery Workflow Generator](https://start.pipery.dev)."
    })
  });

  return { prUrl: mr.web_url, branch, commit: commit.id };
}
